# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Editor_config = debug

else ifeq ($(config),release)
  Editor_config = release

else ifeq ($(config),dist)
  Editor_config = dist

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Editor

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Editor:
ifneq (,$(Editor_config))
	@echo "==== Building Editor ($(Editor_config)) ===="
	@${MAKE} --no-print-directory -C Editor -f Makefile config=$(Editor_config)
endif

clean:
	@${MAKE} --no-print-directory -C Editor -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Editor"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"